### ISSUE TITLE
i cant use the app classs

### ISSUE THREAD

**Issue by osama-raddad** [frostymarvelous/Folio#2]
man you need to remove the Application class from your library and leave it to the users or make App so he can use it

**Comment by thedumbtechguy** [comment]
Have you tried overriding it in your manifest? 
Whatever you are replacing it should extend the App class.

**Comment by osama-raddad** [comment]
what do you mean

**Comment by thedumbtechguy** [comment]
Create your own application class that extends the Folio class and then
specify that the in your manifest.
